### ISSUE TITLE
Crash when i stop the server

### ISSUE THREAD

**Issue by 88tom** [FabioZumbi12/SEDiscordBridge#21]
i'm trying this plugin but when i stop the server all crash with this error (i configured the token and it won't work with discord, the bot stay offline):

12:24:13.8013 [ERROR]  Torch.Session.TorchSessionManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.WebSocket.WebSocketClient.<InternalDisconnectAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<DisconnectAsync>d__238.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.<DisconnectDiscord>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.Stopdiscord()
   at SEDiscordBridge.SEDiscordBridgePlugin.SessionChanged(ITorchSession session, TorchSessionState state)
   at Torch.API.Session.TorchSessionStateChangedDel.Invoke(ITorchSession session, TorchSessionState newState)
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\jenkins\workspace\Torch_Torch_master\Torch\Session\TorchSessionManager.cs:line 176
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.WebSocket.WebSocketClient.<InternalDisconnectAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<DisconnectAsync>d__238.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.<DisconnectDiscord>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.Stopdiscord()
   at SEDiscordBridge.SEDiscordBridgePlugin.SessionChanged(ITorchSession session, TorchSessionState state)
   at Torch.API.Session.TorchSessionStateChangedDel.Invoke(ITorchSession session, TorchSessionState newState)
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\jenkins\workspace\Torch_Torch_master\Torch\Session\TorchSessionManager.cs:line 176
12:24:13.8013 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.WebSocket.WebSocketClient.<InternalDisconnectAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<DisconnectAsync>d__238.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.<DisconnectDiscord>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.Stopdiscord()
   at SEDiscordBridge.SEDiscordBridgePlugin.SessionChanged(ITorchSession session, TorchSessionState state)
   at Torch.API.Session.TorchSessionStateChangedDel.Invoke(ITorchSession session, TorchSessionState newState)
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\jenkins\workspace\Torch_Torch_master\Torch\Session\TorchSessionManager.cs:line 181
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 241
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.WebSocket.WebSocketClient.<InternalDisconnectAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<DisconnectAsync>d__238.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.<DisconnectDiscord>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SEDiscordBridge.DiscordBridge.Stopdiscord()
   at SEDiscordBridge.SEDiscordBridgePlugin.SessionChanged(ITorchSession session, TorchSessionState state)
   at Torch.API.Session.TorchSessionStateChangedDel.Invoke(ITorchSession session, TorchSessionState newState)
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\jenkins\workspace\Torch_Torch_master\Torch\Session\TorchSessionManager.cs:line 181
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 241
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by FabioZumbi12** [comment]
My plugin try to end a non existing connection. Your tokken is incorrect or cant connect to discord. Check this info, token, channel ids and re-check the bot creation tutorial
