### ISSUE TITLE
Shutdown on player connect

### ISSUE THREAD

**Issue by woikal** [FabioZumbi12/SEDiscordBridge#36]
Hi there!
Have it quite regularly (at least once a week), but not reliably, that torchAPI crashes, when a user tries to connect, with the following log entry:

```
16:02:53.2808 [INFO]   Torch.Server.Managers.MultiplayerManagerDedicated: Connection attempt by <<steamID>> from <<player IP>>
16:02:53.2989 [INFO]   Torch.Managers.MultiplayerManagerBase: Player Scytero joined (76561197962528931)
16:03:08.7379 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.DiscordApiClient.PrepareMessage(JToken msg_raw)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Net.DiscordApiClient.PrepareMessage(JToken msg_raw)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
```

Also while it gets started, the bridge does not connect to Discord after the restart:

`16:03:19.3860 [INFO]   SEDiscordBridge.SEDiscordBridgePlugin: Starting Discord Bridge!`

**Comment by FabioZumbi12** [comment]
This should be fixed on pre-release 1.7.0 from here: https://github.com/FabioZumbi12/SEDiscordBridge/releases/tag/1.7.0
