### ISSUE TITLE
Crash when starting up the Server

### ISSUE THREAD

**Issue by Sadragos** [FabioZumbi12/SEDiscordBridge#39]
When using Discord Bridge 1.6.0 with torch 1.3.1.91 the server won't start at all

```
16:40:44.3779 [INFO]   Torch: Torch Version: v1.3.1.91-master
16:40:44.3779 [INFO]   Torch: Game Version: 1.193.21
[...]
16:41:49.7428 [INFO]   SEDiscordBridge.SEDiscordBridgePlugin: Starting Discord Bridge!
16:41:49.9045 [ERROR]  Torch.Session.TorchSessionManager: System.AggregateException: One or more errors occurred. ---> DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<GetChannelAsync>d__240.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.SendStatusMessage(String user, String msg)
   at SEDiscordBridge.SEDiscordBridgePlugin.SessionChanged(ITorchSession session, TorchSessionState state)
   at Torch.API.Session.TorchSessionStateChangedDel.Invoke(ITorchSession session, TorchSessionState newState)
   at Torch.Session.TorchSessionManager.SessionLoaded() in C:\jenkins\workspace\Torch_Torch_master\Torch\Session\TorchSessionManager.cs:line 136
---> (Inner Exception #0) DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<GetChannelAsync>d__240.MoveNext()<---

System.AggregateException: One or more errors occurred. ---> DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<GetChannelAsync>d__240.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.SendStatusMessage(String user, String msg)
   at SEDiscordBridge.SEDiscordBridgePlugin.SessionChanged(ITorchSession session, TorchSessionState state)
   at Torch.API.Session.TorchSessionStateChangedDel.Invoke(ITorchSession session, TorchSessionState newState)
   at Torch.Session.TorchSessionManager.SessionLoaded() in C:\jenkins\workspace\Torch_Torch_master\Torch\Session\TorchSessionManager.cs:line 136
---> (Inner Exception #0) DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<GetChannelAsync>d__240.MoveNext()<---

16:41:49.9045 [FATAL]  Initializer: DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<GetChannelAsync>d__240.MoveNext()
DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<GetChannelAsync>d__240.MoveNext()
16:41:49.9165 [INFO]   Initializer: Generating minidump at d:\servers\service12914\home\games\se_torch\Minidump.dmp
16:41:49.9165 [ERROR]  Initializer: Keen broke the minidump, sorry.
16:46:43.2895 [INFO]   SteamCMD: Checking for DS updates.
16:46:46.8394 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
```

**Comment by Sadragos** [comment]
Same Issue with Torch Version: v1.3.1.92-master

**Comment by FabioZumbi12** [comment]
Following #38

**Comment by FabioZumbi12** [comment]
This is caused by a channel not found when sedb try to send the status message to discord! Check your channels ids and reocnfigure. Btw, i've added a caught for this errors to do not crash the server. 

Use this version to avoid this: https://github.com/FabioZumbi12/SEDiscordBridge/releases/tag/1.7.0
