### ISSUE TITLE
Errors dump to bridge chat instead of logs

### ISSUE THREAD

**Issue by kontu** [FabioZumbi12/SEDiscordBridge#48]
Whenever the bridge errors (we see the below ones usually when Discord is congested/takes too long to respond, but that's not the point of the ticket) -- it dumps it to game chat.

Can we please get this to just go to logs instead of spamming a 13 line stacktrace to in game chat and the discord channel?

`[11:56 AM] BOT Lambda Draconis: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d39.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.<>cDisplayClass26_0.<SendChatMessage>b0()
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d39.MoveNext()<---
[11:56 AM] BOT Delta Draconis: Ebass: Discord dead
[11:56 AM] BOT Lambda Draconis: electrobombs: its that covid connection
[11:56 AM] BOT Delta Draconis: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d39.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.<>cDisplayClass26_0.<SendChatMessage>b0()
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d39.MoveNext()<---`

**Comment by FabioZumbi12** [comment]
Should be on latest pre=release: https://github.com/FabioZumbi12/SEDiscordBridge/releases

**Comment by FabioZumbi12** [comment]
SEDB is now maintained by Bishbash777 on https://github.com/Bishbash777/SEDB-RELOADED
