### ISSUE TITLE
FormatException when sending server message

### ISSUE THREAD

**Issue by theCalcaholic** [FabioZumbi12/SEDiscordBridge#9]
I get the following exception whenever the plugin is trying to send a server message:

Does it maybe get the system time in a wrong format (not month/day/year)?

```
13:22:55.7553 [FATAL]  Initializer: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at SEDiscordBridge.DiscordBridge.SendStatusMessage(String user, String msg) in D:\SpaceEngineersMod\TorchPlugins\SEDiscordBridge\SEDiscordBridge\DiscordBridge.cs:line 97
   at SEDiscordBridge.SEDicordBridgePlugin._multibase_PlayerJoined(IPlayer obj) in D:\SpaceEngineersMod\TorchPlugins\SEDiscordBridge\SEDiscordBridge\SEDicordBridgePlugin.cs:line 175
   at Torch.Managers.MultiplayerManagerBase.RaiseClientJoined(UInt64 steamId)
   at Torch.Server.Managers.MultiplayerManagerDedicated.RunEvent(ValidateAuthTicketEvent info)
   at Torch.Server.Managers.MultiplayerManagerDedicated.ValidateAuthTicketResponse(UInt64 steamId, JoinResult response, UInt64 steamOwner)
   at SteamSDK.GameServer.validateAuthTicketResponse(GameServer owner, ValidateAuthTicketResponse_t* data)
   at CCallback<SteamSDK::Callback<SteamSDK::GameServer,ValidateAuthTicketResponse_t,1>,ValidateAuthTicketResponse_t,1>.Run(CCallback<SteamSDK::Callback<SteamSDK::GameServer\,ValidateAuthTicketResponse_t\,1>\,ValidateAuthTicketResponse_t\,1>* , Void* pvParam)
   at SteamGameServer_RunCallbacks()
   at VRage.Steam.MySteamService.Update()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart()
   at Torch.VRageGame.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at SEDiscordBridge.DiscordBridge.SendStatusMessage(String user, String msg) in D:\SpaceEngineersMod\TorchPlugins\SEDiscordBridge\SEDiscordBridge\DiscordBridge.cs:line 97
   at SEDiscordBridge.SEDicordBridgePlugin._multibase_PlayerJoined(IPlayer obj) in D:\SpaceEngineersMod\TorchPlugins\SEDiscordBridge\SEDiscordBridge\SEDicordBridgePlugin.cs:line 175
   at Torch.Managers.MultiplayerManagerBase.RaiseClientJoined(UInt64 steamId)
   at Torch.Server.Managers.MultiplayerManagerDedicated.RunEvent(ValidateAuthTicketEvent info)
   at Torch.Server.Managers.MultiplayerManagerDedicated.ValidateAuthTicketResponse(UInt64 steamId, JoinResult response, UInt64 steamOwner)
   at SteamSDK.GameServer.validateAuthTicketResponse(GameServer owner, ValidateAuthTicketResponse_t* data)
   at CCallback<SteamSDK::Callback<SteamSDK::GameServer,ValidateAuthTicketResponse_t,1>,ValidateAuthTicketResponse_t,1>.Run(CCallback<SteamSDK::Callback<SteamSDK::GameServer\,ValidateAuthTicketResponse_t\,1>\,ValidateAuthTicketResponse_t\,1>* , Void* pvParam)
   at SteamGameServer_RunCallbacks()
   at VRage.Steam.MySteamService.Update()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart()
   at Torch.VRageGame.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by theCalcaholic** [comment]
Ah, stupid me - I put in the channel names instead of their ids.
